/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
 */

@interface UIKitDebugHierarchyMetaDataProvider : NSObject <DebugHierarchyMetaDataProvider_Fallback>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)fallback_debugHierarchyEnumDescriptions;
+ (id)fallback_debugHierarchyOptionDescriptions;

@end
