/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCoreMIDI.dylib
 */

@interface _TtCE8CoreMIDIVSo14MIDIPacketList7Builder : Swift._SwiftObject {
    void packetListPointer;
}

@end
