/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface _NSKeyValueObservation : NSObject {
    void helper;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (void)invalidate;

@end
