/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface _TtC10FoundationP33_45BFD3D387700B862E3A7353B97EF7ED21__CharacterSetStorage : Swift._SwiftObject {
    void _backing;
}

@end
