/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface _TtCE10FoundationCSo7NSTimer14TimerPublisher : Swift._SwiftObject {
    void $__lazy_storage_$_routingSubscription;
    void interval;
    void mode;
    void options;
    void runLoop;
    void tolerance;
}

@end
