/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface _TtC10FoundationP33_12768CA107A31EF2DCE034FD75B541C913__JSONDecoder : Swift._SwiftObject {
    void codingPath;
    void options;
    void storage;
}

@end
