/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface _TtC10FoundationP33_5692656F4C05BA2A580AE9322E9FB0A614__PlistEncoder : Swift._SwiftObject {
    void codingPath;
    void options;
    void storage;
}

@end
