/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface _TtC10FoundationP33_AE6BD10245B422606B9EE93C01570D8F21_CombineRunLoopAction : NSObject {
    void action;
}

- (void).cxx_destruct;
- (id)init;

@end
