/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface Foundation.__JSONEncoder : Swift._SwiftObject {
    void dataEncodingStrategy;
    void dateEncodingStrategy;
    void keyEncodingStrategy;
    void nonConformingFloatEncodingStrategy;
    void outputFormatting;
    void userInfo;
}

@end
