/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface Foundation.__JSONDecoder : Swift._SwiftObject {
    void dataDecodingStrategy;
    void dateDecodingStrategy;
    void keyDecodingStrategy;
    void nonConformingFloatDecodingStrategy;
    void userInfo;
}

@end
