/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftFoundation.dylib
 */

@interface Foundation.__DataStorage : Swift._SwiftObject {
    void _bytes;
    void _capacity;
    void _deallocator;
    void _length;
    void _needToZero;
    void _offset;
}

@end
