/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftAccelerate.dylib
 */

@interface _TtCO10Accelerate4vDSP3DCT : Swift._SwiftObject {
    void dctSetup;
}

@end
