/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libnetwork.dylib
 */

@interface OS_nw_array : OS_object

- (void)dealloc;

// OS_nw_array (nw_descriptions)

- (id)description;
- (id)redactedDescription;

@end
