/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libxpc.dylib
 */

@interface OS_xpc_event_publisher : OS_object

- (void)_xref_dispose;
- (void)dealloc;
- (id)description;
- (id)init;
- (oneway void)release;

@end
