/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection/libdispatch.dylib
 */

@interface OS_voucher : OS_object

- (void)dealloc;
- (id)debugDescription;
- (id)init;
- (oneway void)release;
- (id)retain;

@end
