/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libAXSpeechManager.dylib
 */

@interface AXSpeechThread : NSThread {
    NSPort * _machPort;
    NSRunLoop * _threadRunLoop;
}

- (void).cxx_destruct;
- (void)cancel;
- (id)init;
- (void)main;
- (void)stop;

@end
