/* Generated by RuntimeBrowser.
 */

@protocol MTLRenderPipelineStateSPI <MTLRenderPipelineState>

@required

- (MTLDebugInstrumentationData *)fragmentDebugInstrumentationData;
- (NSData *)newFragmentShaderDebugInfo;
- (NSData *)newVertexShaderDebugInfo;
- (unsigned long long)uniqueIdentifier;
- (MTLDebugInstrumentationData *)vertexDebugInstrumentationData;

@optional

- (unsigned long long)resourceIndex;
- (void)setResourceIndex:(unsigned long long)arg1;

@end
