/* Generated by RuntimeBrowser.
 */

@protocol NSFetchedResultsControllerDelegate <NSObject>

@optional

- (void)controller:(id)arg1 didChangeContentWithDifference:(NSOrderedCollectionDifference *)arg2;
- (void)controller:(id)arg1 didChangeContentWithDifference:(NSOrderedCollectionDifference *)arg2;
- (void)controller:(id)arg1 didChangeContentWithSnapshot:(NSDiffableDataSourceSnapshot *)arg2;
- (void)controller:(id)arg1 didChangeContentWithSnapshot:(NSDiffableDataSourceSnapshot *)arg2;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(NSIndexPath *)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(NSIndexPath *)arg5;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(NSIndexPath *)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(NSIndexPath *)arg5;
- (void)controller:(id)arg1 didChangeSection:(id <NSFetchedResultsSectionInfo>)arg2 atIndex:(long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controller:(id)arg1 didChangeSection:(id <NSFetchedResultsSectionInfo>)arg2 atIndex:(long long)arg3 forChangeType:(unsigned long long)arg4;
- (NSString *)controller:(id)arg1 sectionIndexTitleForSectionName:(NSString *)arg2;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1;

@end
