/* Generated by RuntimeBrowser.
 */

@protocol VCHardwareSettingsEmbeddedProtocol

@required

- (long long)chipId;
- (long long)deviceClass;
- (bool)hasAppleNeuralEngine;
- (bool)isDeviceLargeScreen;
- (bool)isSecondDisplaySupportEnabled;
- (unsigned int)maxActiveVideoDecoders;
- (unsigned int)maxActiveVideoEncoders;
- (int)screenHeight;
- (int)screenWidth;
- (bool)supportsHEIFEncoding;
- (bool)useSoftFramerateSwitching;
- (long long)videoEncoderType;

@end
