/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCoreMedia.dylib
 */

@interface _TtCVE9CoreMediaaSo22CMFormatDescriptionRef22ParameterSetCollectionP33_B5107634416AF8266ECF5CD01992F6B819CachedParameterSets : Swift._SwiftObject {
    void parameterSets;
}

@end
