/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMobileGestaltExtensions.dylib
 */

@interface MobileGestaltHelperProxy : NSObject {
    NSXPCConnection * _connection;
    int  _error;
    <MobileGestaltHelper> * _helper;
}

@property (readonly) NSXPCConnection *connection;
@property int error;
@property (readonly) <MobileGestaltHelper> *helper;

+ (id)proxy;

- (id)connection;
- (void)dealloc;
- (int)error;
- (id)helper;
- (id)init;
- (void)invalidate;
- (bool)proxyRebuildCache;
- (void)setError:(int)arg1;

@end
