/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftDispatch.dylib
 */

@interface Dispatch._DispatchWorkItem : Swift._SwiftObject {
    void _block;
}

@end
