/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCoreAudio.dylib
 */

@interface _TtCV9CoreAudio25ManagedAudioChannelLayoutP33_429D68E17F2C221C283DB52CAE70232C7Storage : Swift._SwiftObject {
    void audioChannelLayoutPointer;
    void deallocator;
}

@end
