/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
 */

@interface __SwiftValue : NSObject <NSCopying>

+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (const struct TargetMetadata<swift::InProcess> { unsigned long long x1; }*)_swiftTypeMetadata;
- (id)_swiftTypeName;
- (const struct OpaqueValue { }*)_swiftValue;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@end
