/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
 */

@interface __SwiftNativeNSError : NSError

+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (Class)classForCoder;
- (long long)code;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)domain;
- (bool)isEqual:(id)arg1;
- (id)userInfo;

@end
