/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
 */

@interface _TtCVVs17__CocoaDictionary5Index7Storage : Swift._SwiftObject {
    void allKeys;
    void base;
}

@end
