/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
 */

@interface _TtCVs17__CocoaDictionary8Iterator : Swift._SwiftObject {
    void _fastEnumerationStackBuf;
    void _fastEnumerationState;
    void base;
    void itemCount;
    void itemIndex;
}

@end
