/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
 */

@interface Swift.__stdlib_ReturnAutoreleasedDummy : Swift._SwiftObject

- (id)init;
- (id)returnsAutoreleased:(id)arg1;

@end
