/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
 */

@interface Swift.__RawDictionaryStorage : Swift.__SwiftNativeNSDictionary {
    void _age;
    void _capacity;
    void _count;
    void _extra;
    void _rawKeys;
    void _rawValues;
    void _reservedScale;
    void _scale;
    void _seed;
}

- (id)initWithCoder:(id)arg1;

@end
