/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libAudioStatistics.dylib
 */

@interface CAReportingPerformanceObject : NSObject {
    NSDictionary * _configuration;
    NSString * _perfDataName;
    NSString * _perfDataPath;
    NSDictionary * _performanceMetrics;
    NSArray * _processIdentifiers;
    unsigned short  _serviceType;
}

@property (nonatomic, retain) NSDictionary *configuration;
@property (retain) NSString *perfDataName;
@property (retain) NSString *perfDataPath;
@property (nonatomic, readonly) NSDictionary *performanceMetrics;
@property (retain) NSArray *processIdentifiers;
@property (nonatomic) unsigned short serviceType;

- (void).cxx_destruct;
- (void)begin;
- (id)configuration;
- (id)endAndReturnPerformanceMetrics;
- (id)initWithProcessIdentifiers:(id)arg1;
- (id)perfDataName;
- (id)perfDataPath;
- (id)performanceMetrics;
- (id)processIdentifiers;
- (unsigned short)serviceType;
- (void)setConfiguration:(id)arg1;
- (void)setPerfDataName:(id)arg1;
- (void)setPerfDataPath:(id)arg1;
- (void)setProcessIdentifiers:(id)arg1;
- (void)setServiceType:(unsigned short)arg1;

@end
