/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libAudioStatistics.dylib
 */

@interface CATestReporter : CAReporter

- (id)initWithNewReporterID;
- (id)initWithReporterID:(long long)arg1 serviceType:(unsigned short)arg2;
- (void)setServiceType:(unsigned short)arg1;

@end
