/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib
 */

@interface __NSUnrecognizedTaggedPointer : NSObject

- (id)autorelease;
- (oneway void)release;
- (id)retain;

@end
